# Generated by Django 3.2.5 on 2022-01-06 18:23

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='user_pro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, max_length=200)),
                ('profile_pic', models.ImageField(blank=True, upload_to=accounts.models.path_and_rename, verbose_name='profile_picture')),
                ('user_type', models.CharField(choices=[('teacher ', 'teacher'), ('student', 'student'), ('parent', 'parent')], default='student', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
