# Generated by Django 3.2.5 on 2022-01-22 05:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_pro',
            new_name='UserPro',
        ),
    ]
