# Generated by Django 3.2.5 on 2022-01-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spehr', '0002_auto_20220108_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empolyee',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
