# Generated by Django 3.2.5 on 2022-01-22 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spehr', '0003_alter_empolyee_create_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='identify',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
