# Generated by Django 3.2.5 on 2022-01-24 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spehr', '0004_identify_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empolyee',
            name='emp_pic',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='emp pic'),
        ),
        migrations.AlterField(
            model_name='empolyee',
            name='id_card_pic',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='ID Image'),
        ),
    ]
